WarGameSimulation.SCENARIO_PRESETS = {
  pre_war: {
    description: "Pre-war baseline: Full Iranian military intact, diplomatic tensions",
    initial_escalation: 0,
    us_force_multiplier: 1.0,
    iran_force_multiplier: 1.0,
    escalation_propensity: 0.5,
    iran_asymmetric_factor: 1.0,
    max_days: 90,
  },
  epic_fury_day1: {
    description: "Operation Epic Fury Day 1 (Feb 28, 2026): Surprise opening strikes, Khamenei killed",
    initial_escalation: 6,
    us_force_multiplier: 1.2,
    iran_force_multiplier: 0.85,
    escalation_propensity: 0.9,
    cyber_intensity: 0.9,
    us_sead_effectiveness: 0.95,
    iran_ad_lethality: 0.10,
    us_tech_advantage: 1.8,
    max_days: 35,
  },
  epic_fury_day5: {
    description: "Operation Epic Fury Day 5 (Mar 4, 2026): Iran navy destroyed, air force destroyed, IADS neutralized",
    initial_escalation: 6,
    us_force_multiplier: 1.3,
    iran_force_multiplier: 0.25,
    proxy_effectiveness: 0.5,
    escalation_propensity: 0.2,
    cyber_intensity: 0.95,
    us_sead_effectiveness: 0.99,
    iran_ad_lethality: 0.02,
    iran_asymmetric_factor: 0.8,
    us_tech_advantage: 2.0,
    hormuz_mining_probability: 0.4,
    iran_mine_warfare_effectiveness: 0.3,
    nuclear_threshold_probability: 0.01,
    patriot_intercept_rate: 0.92,
    max_days: 30,
  },
  epic_fury_day7: {
    description: "Operation Epic Fury Day 7 (Mar 5, 2026): Full air superiority, Hormuz fully closed, mop-up phase",
    initial_escalation: 6,
    us_force_multiplier: 1.35,
    iran_force_multiplier: 0.15,
    proxy_effectiveness: 0.35,
    escalation_propensity: 0.15,
    cyber_intensity: 0.98,
    us_sead_effectiveness: 1.0,
    iran_ad_lethality: 0.01,
    iran_asymmetric_factor: 0.6,
    us_tech_advantage: 2.2,
    hormuz_mining_probability: 0.3,
    iran_mine_warfare_effectiveness: 0.2,
    nuclear_threshold_probability: 0.005,
    patriot_intercept_rate: 0.94,
    max_days: 25,
  },
  what_if_ground_invasion: {
    description: "What-if: US escalates to ground invasion after air campaign",
    initial_escalation: 6,
    us_force_multiplier: 1.5,
    iran_force_multiplier: 0.3,
    escalation_propensity: 0.95,
    nuclear_threshold_probability: 0.15,
    max_days: 120,
  },
  limited: {
    description: "Limited Naval Confrontation: Contained to Persian Gulf maritime clashes",
    initial_escalation: 4,
    escalation_propensity: 0.3,
    us_force_multiplier: 1.0,
    iran_force_multiplier: 1.0,
    proxy_effectiveness: 0.4,
    cyber_intensity: 0.3,
    iran_asymmetric_factor: 1.3,
    us_tech_advantage: 1.5,
    nuclear_threshold_probability: 0.02,
    max_days: 60,
  },
  escalatory: {
    description: "Rapid Escalation Spiral: Fast climb through escalation levels",
    initial_escalation: 5,
    escalation_propensity: 0.8,
    us_force_multiplier: 1.2,
    iran_force_multiplier: 1.0,
    proxy_effectiveness: 0.8,
    cyber_intensity: 0.7,
    iran_asymmetric_factor: 1.3,
    us_tech_advantage: 1.5,
    nuclear_threshold_probability: 0.1,
    max_days: 90,
  },
  proxy: {
    description: "Proxy War Focus: Iran fights through Hezbollah, Houthis, and Iraqi militias",
    initial_escalation: 3,
    escalation_propensity: 0.4,
    us_force_multiplier: 0.8,
    iran_force_multiplier: 0.8,
    proxy_effectiveness: 1.0,
    cyber_intensity: 0.5,
    iran_asymmetric_factor: 1.5,
    us_tech_advantage: 1.3,
    nuclear_threshold_probability: 0.03,
    max_days: 120,
  },
  worst: {
    description: "Worst Case Scenario: Maximum Iranian capability, full proxy activation, high nuclear risk",
    initial_escalation: 6,
    escalation_propensity: 0.95,
    us_force_multiplier: 1.0,
    iran_force_multiplier: 1.3,
    proxy_effectiveness: 1.0,
    cyber_intensity: 0.9,
    iran_asymmetric_factor: 1.6,
    us_tech_advantage: 1.4,
    nuclear_threshold_probability: 0.15,
    max_days: 90,
  },
};


// ── Historical Validation Presets ──
// Calibrated to known conflicts for model validation
WarGameSimulation.VALIDATION_PRESETS = {
  desert_storm_1991: {
    description: "Desert Storm (1991): 43-day air + 100-hour ground campaign. Known: ~300 US KIA, ~25,000 Iraqi KIA",
    initial_escalation: 5,
    us_force_multiplier: 1.4,
    iran_force_multiplier: 0.8,
    us_tech_advantage: 2.0,
    escalation_propensity: 0.3,
    nuclear_threshold_probability: 0.001,
    proxy_effectiveness: 0.2,
    cyber_intensity: 0.05,
    iran_asymmetric_factor: 0.5,
    oil_price_elasticity: -0.08,
    max_days: 43,
    // Acceptance criteria:
    // US casualties: 50-600
    // Iraqi casualties: 10,000-50,000
    // Ratio: 20:1 - 120:1
  },
  iraq_2003: {
    description: "Iraq 2003: 21-day invasion phase. Known: ~140 US KIA, ~7,600-10,800 Iraqi KIA",
    initial_escalation: 5,
    us_force_multiplier: 1.5,
    iran_force_multiplier: 0.7,
    us_tech_advantage: 1.8,
    escalation_propensity: 0.2,
    nuclear_threshold_probability: 0.001,
    proxy_effectiveness: 0.15,
    cyber_intensity: 0.1,
    iran_asymmetric_factor: 0.6,
    oil_price_elasticity: -0.06,
    max_days: 21,
    // Acceptance criteria:
    // US casualties: 50-300
    // Iraqi casualties: 5,000-15,000
  },
};
